Homework 1
LeovanGit/render_internship pull request #1
Opened 2022-05-03 14:38 UTC by LeovanGit

2022-05-03 17:49 UTC, mrindieperson commented
Из под Visual Studio не собирается

2022-05-03 18:12 UTC, mrindieperson requested changes

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +int delta_mouse_y = 0;
Весь input state, всё что связано с управлением, инкапсулируй в классе Controller. Этот класс будет содержать высокоуровневый код игровой логики. Именно Controller должен инициализировать сцену и управлять ею. Controller может получить ссылку/указатель на Scene и обращаться к её данным

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +Sphere sphere(100, vec3(0, 0, 0));
Инкапсулируй рисуемые объекты в класс Scene, у которой есть метод draw/render

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +    pixels = nullptr;
Никогда не используй new, используй unique_ptr.
А тут вообще можно просто vector интов объявить для пикселей.
И зачем вообще аллоцировать и освобождать память каждый кадр, если можно переиспользовать? Аллокация - долгая операция, затрагивающая ОС

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +            float discriminant = b * b - 4 * a * c;
Инкапсулируй функцию нахождения пересечения луча и сферы в Sphere::intersection/hit, которая принимает луч как аргумент

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +    uint32_t * pixels = new uint32_t[client_width * client_height * 4];
Инкапсулируй все ресурсы окна, hdc, mbi, pixels в класс Window как минимум с методами resize, getPixels, getSize и т.п.

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +    SetDIBitsToDevice(hdc,
Инкапсулируй вызов SetDIBitsToDevice в Window::flush

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +        calc_delta_time();
Добавь стабильный 60 FPS, нужно только по прошествии FRAME_DURATION = 1.f / 60.f секунд рисовать кадр снова

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +void move()
Все такие функции управления инкапсулируй в Controller::processInput

2022-05-03 18:12 UTC, mrindieperson commented on homework-1/engine/src/engine.cpp
> +        if(PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
Здесь нужен while, чтобы все сообщения в очереди обработать, они могут быстрее приходить, чем FPS в игре будет

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +int delta_mouse_y = 0;
++

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +Sphere sphere(100, vec3(0, 0, 0));
++

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +    pixels = nullptr;
++

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +            float discriminant = b * b - 4 * a * c;
++

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +    uint32_t * pixels = new uint32_t[client_width * client_height * 4];
++

2022-05-05 11:59 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +    SetDIBitsToDevice(hdc,
++

2022-05-05 12:00 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +        calc_delta_time();
++

2022-05-05 12:00 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +void move()
++

2022-05-05 12:00 UTC, LeovanGit commented on homework-1/engine/src/engine.cpp
> +        if(PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
++

2022-05-05 12:43 UTC, mrindieperson commented
Вынеси Controller/Scene/Window в разные файлы, не держи всё в одном engine.cpp

2022-05-05 12:53 UTC, mrindieperson commented on homework-1/engine/src/main.cpp
> +    float current_time = GetTickCount();
Вместо всего этого используй std::chrono, пожалуйста, в частности steady_clock. Там понадобится делать duration_cast\<float\> между моментами времени и сравнивать разницу времени с константой const float FRAME_DURATION = 1.f / 60.f;

2022-05-05 13:21 UTC, mrindieperson commented
Не забывай параметры передавать как const& для типов больших, чем размер указателя

2022-05-05 17:46 UTC, LeovanGit commented on homework-1/engine/src/main.cpp
> +    float current_time = GetTickCount();
++

2022-05-05 18:00 UTC, mrindieperson approved these changes

2022-05-05 18:03 UTC, merged