Homework 2
LeovanGit/render_internship pull request #2
Opened 2022-05-23 12:06 UTC by LeovanGit

2022-05-25 21:27 UTC, Bonefest requested changes
Также, как указывал Эмиль, используй везде cosf, sinf и т.д

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/inc/camera.hpp
> +           glm::vec3 up,
Структуры данных, размеры которых больше 32х/64х бит (в зависимости от разрядности), лучше передавать по ссылке, чтобы избежать копирования.

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/inc/material.hpp
> +             float glossiness,
Та же ситуация: передавай вектора по ссылке. Больше не буду писать подобные комментарии, но у тебя это почти в каждом конструкторе.

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/src/camera.cpp
> +    rotation = glm::quat(cos(glm::radians(angles.z / 2)),
Расчёт кватерниона по углам Эйлера у тебя в паре месте происходит. Было бы ок вынести в какую-нибудь общую функцию, например quatFromEuler(yaw, pitch, roll)

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/src/camera.cpp
> +void Camera::setWorldAngles(const glm::vec3 & angles)
Чтобы точно не возникало сомнений, лучше либо создай новую структуру EulerAngles, которая хранит yaw, pitch, roll углы либо передавай в setWorldAngles три float32 с соответствующими названиями.

Может такое быть, что кто-то подразумевает какой-то другой порядок для angles.xyz, например что angles.x отвечает за roll.

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/src/controller.cpp
> +            glm::vec4 dir_cs(xy.x, xy.y, 1.0f, 1.0f);
Этот код повторяется в двух местах (ещё в рендеринге). Лучше вынести генерацию луча в отдельное место, например, в камеру: camera->generateWorldRayFromNDC(xyNDC)

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/src/math/plane.cpp
> +    if (d == 0) return false;
Не сравнивай вещественные значения напрямую. лучше создать функцию что-то в духе bool areAlmostEqual(float1, float2, tolerance);, например areAlmostEqual(1, 1.00001, 0.01) вернет true. Но учти, что даже это решение имеет свои нюансы.

Если интересно, здесь можно почитать более детально: http://www.r-5.org/files/books/computers/algo-list/realtime-3d/Christer_Ericson-Real-Time_Collision_Detection-EN.pdf (глава 11.3)

2022-05-25 21:27 UTC, Bonefest commented on homework-2/engine/src/math/sphere.cpp
> +    float b = 2.0f * glm::dot(ray.direction, L);
Код поиска пересечения сферы можно чуть упростить (видно с формулы) - можно вынести 4 с дискриминанта и затем 2 вообще за скобки. Тогда 2 сократится с знаменателем. Другими словами, не умножай на 2 в b, не умножай на 4 в discrimant, и вообще не дели ни на что в t_near (т.к a = 1, а 2 - сократилось).

2022-05-25 22:34 UTC, mrindieperson commented on homework-2/engine/src/math/plane.cpp
> +    if (d == 0) return false;
не лучше, а это обязательно надо делать, так как это условие не будет срабатывать в 99.99999999999% случаев. Это надо навсегда запомнить, что нельзя флоты сравнивать через ==, если происходили какие-то операции над флотами

2022-05-25 22:37 UTC, mrindieperson commented
Не добавил рендер в уменьшенное разрешение в 2 раза по каждой оси для повышения производительности при помощи StretchDIBits

2022-05-25 22:41 UTC, mrindieperson commented
Не надо в каждом задании переименовывать папку, переименуй один раз в project и всё

2022-05-25 22:44 UTC, mrindieperson commented
У тебя же вращение неправильно работает. Поверни на 90 градусов вправо камеру на старте, а потом мышью попробуй посмотреть вверх

2022-05-25 22:45 UTC, mrindieperson commented
Когда захватываю объект и пытаюсь одновременно двигать/вращать камеру, расстояние до захваченной точки не сохраняется, должно оставаться на той же дистанции от камеры. Это всё можно сделать используя одно только значение t из рейкаста

2022-05-25 22:47 UTC, mrindieperson commented on homework-2/engine/src/main.cpp
> +    std::vector<Material> materials;
Всю инициализацию объектов и освещения сцены инкапсулируй в Controller::initScene

2022-05-25 22:56 UTC, mrindieperson commented on homework-2/engine/src/controller.cpp
> +        speed.x = (delta_fixed_mouse.y / (float)height) * 360;
Магические константы, добавь явно rotationSpeed как поле Controller, как и movementSpeed

2022-05-25 22:58 UTC, mrindieperson commented on homework-2/engine/inc/controller.hpp
> +constexpr int KEY_RMOUSE = 2;
Локальные константы в .cpp файлах и прочие локальные функции засовывай в безымянный неймспейс, чтобы они не линковались с одноимёнными вероятными идентификаторами в хидерах, если это не нужно

2022-05-25 23:01 UTC, mrindieperson commented on homework-2/engine/src/controller.cpp
> +        xy.y = 1.0f - 2.0f * mouse.y / height; // reversed
Поправь каст лучей из пикселей, как я в чате писал. Нужно 0.5f прибавлять к координатам пикселей перед переводом в ClipSpace, иначе это не центр пикселя

2022-05-25 23:15 UTC, mrindieperson commented on homework-2/engine/src/scene.cpp
> +            glm::vec4 dir_ws = camera.getViewProjInv() * dir_cs;
можно оптимизировать чуть рендер и уменьшить число матричных умножений, если, как я ещё в видосе объяснял, вычислить векторы nearPlaneRight и nearPlaneTop и находить точку на nearPlane как nearPlaneBottomLeft + pixelX * nearPlaneRight + pixelY * nearPlaneTop

2022-05-25 23:17 UTC, mrindieperson commented on homework-2/engine/src/scene.cpp
> +            (float)pow(cosb, material->glossiness) *
Чем кастовать к (float)x, лучше сконструировать float(x).
А вообще powf используй и все функции с f постфиксами

2022-05-26 09:11 UTC, mrindieperson commented
В VS solution сделай, во-первых, отображение файлов в папках как они находятся в репозитории проекта, то есть math/cube,cpp, например.

Во-вторых: в VS solution не видно хидеры.

В-третьих, не дели плиз .hpp и .cpp на разные хидеры, пускай всё в engine будет, а не в engine/src и engine/inc, объедини

2022-05-30 09:04 UTC, Bonefest approved these changes
Посмотрел, вроде, всё. Всё работает и выглядит прекрасно.

Единственный вопрос на понимание. Ты понимаешь из-за чего у тебя "зажатые" на ПКМ объекты не двигаются во время движения камеры? Если да, какие варианты решения есть?

2022-05-30 09:04 UTC, Bonefest commented on project/engine/main.cpp
>  #define CLIENT_WIDTH 384
Предпочитай constexpr, т.к использование макросов чревато проблемами.

2022-05-30 09:04 UTC, Bonefest commented on project/engine/math/triangle.cpp
> +    if (math::areAlmostEqual(cosa, 0, 0.000001f)) return false;
Точность вынеси в константу. В случае с 0, можешь даже создать ещё одну функцию типа isZero.

2022-05-30 11:06 UTC, LeovanGit commented on project/engine/main.cpp
>  #define CLIENT_WIDTH 384
Я использую их один раз на всю программу, что бы создать первоначальное окно. Стоит ли их выносить в константы?

2022-05-30 16:39 UTC, Bonefest commented on project/engine/main.cpp
>  #define CLIENT_WIDTH 384
Обязательно, макросы полезны только в случае, когда ты используешь вещи типа #ifdef #if и т.д

2022-05-30 17:08 UTC, mrindieperson commented on project/engine/scene.cpp
> +    glm::vec3 top_left_WS = camera.generateWorldPointFromCS(-1.0f, 1.0f);
просто reproject() можно назвать

2022-05-30 17:12 UTC, mrindieperson commented
Approved 👍

2022-05-30 17:13 UTC, mrindieperson approved these changes

2022-05-31 14:36 UTC, merged

2022-05-31 14:38 UTC, Bonefest approved these changes

2022-05-31 14:38 UTC, Bonefest commented
Approved