Homework 3
LeovanGit/render_internship pull request #3
Opened 2022-06-16 00:32 UTC by LeovanGit

2022-06-16 15:35 UTC, Bonefest requested changes
В целом, у тебя код для расчёта BRDF повторяется в 4х местах. Разбей BRDF на функции LambertBRDF, CookTorranceBRDF, ... и используй их

2022-06-16 15:35 UTC, Bonefest commented on project/engine/controller.cpp
> +        camera.EV_100 += 0.1f;
Скорость изменения будет зависеть от fps. Лучше либо умножай на дельту либо вообще меняй только при нажатии.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/main.cpp
> +                controller.scene->is_smooth_reflection =
Контроллер должен сам решать что означает "кнопка R нажата". Тут несколько вариантов: либо сделай в нем onKeyPressed функцию либо можешь пойти дальше и создать класс, который будет представлять событие, а далее эти события передавать по лесенке приложение-игра-контроллер и т.д. Второй вариант можно реализовать разными способами, например сначала собирать события в буфер и обрабатывать только раз в кадр или триггерить сразу.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/material.cpp
>                     glossiness(glossiness),
Перейди на roughness

2022-06-16 15:35 UTC, Bonefest commented on project/engine/math/ray.cpp
> +    const float PI = atanf(1.0f) * 4.0f;
Вынеси Pi отдельно в мат. файл. А ещё лучше, используй либо пи со стандартной библиотеки либо с glm (который, вроде, и golden ratio определяет).

И определять PI таким способом красиво, но использовать константу безопасней.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/math/ray.hpp
> +inline glm::vec3 reflect(const glm::vec3 & ray,
glm должен иметь эту функцию.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/math/ray.hpp
> +void onb_frisvad(const glm::vec3 & normal,
Вынеси эту и следующую функции куда-то отдельно, в общий мат. файл. Им точно здесь не место

2022-06-16 15:35 UTC, Bonefest commented on project/engine/math/triangle.cpp
> +    constexpr float epsilon = 0.000001f;
У тебя эта константа повторяется несколько раз. Сама идея в том, что мы выносим в константу, чтобы не повторяться и  иметь возможность быстро поменять значение. Я бы вынес эпсилон куда-то в одно место

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.hpp
> +const float PI = atanf(1.0f) * 4.0f;
Уже писал про PI выше. И не повторяйся)

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.hpp
> +        float calculateIntensity(const glm::vec3 & point)
То, что считает эта функция, не называется интенсивностью. Интенсивность достаточно перегруженный термин, но в целом это плотность (угловая или пространственная) входящей энергии за единицу времени. Ты скорее считаешь что-то в духе углового затухания

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.cpp
> +    glm::vec3 specular = D * F * G / (4 * NV * NL + epsilon);
Сократи на NL, как ты делаешь в других местах, и epsilon не нужен будет

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.cpp
> +                                                   glm::cos(angle),
cos(angle) можно посчитать быстрее. Скажем, без необходимости считать asin. Посмотри внимательно как.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.cpp
> +        if (!isVisible(nearest, glm::normalize(L))) continue;
Ты normalize(L) считаешь пару раз. Достаточно это сделать один раз + в этот же момент рассчитать длину L.

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.cpp
> +        float solid_angle = (PI * s_lights[i].radius * s_lights[i].radius) /
Считай solid angle где-то в функции, чтобы не повторять код в разных местах

2022-06-16 15:35 UTC, Bonefest commented on project/engine/scene.cpp
> +        material.glossiness > SMOOTHNESS_THRESHOLD &&
Не усложняй, используй roughness

2022-06-18 12:57 UTC, Bonefest requested changes

2022-06-18 12:57 UTC, Bonefest commented on project/engine/math/hemisphere_ray_generation.cpp
> +    float phi = 2 * glm::pi<float>() * sample / glm::golden_ratio<float>();
Чтобы не писать glm::pi<float>(), можешь в своём math спейса написать что-то в духе constexpr float kPif = glm::pi<float>(). Это может немного наложить ограничения на версию компилятор, но будет читаться гораздо проще

2022-06-18 12:57 UTC, Bonefest commented on project/engine/math/hemisphere_ray_generation.cpp
> +    glm::vec3 point(cos(phi) * sin(theta),
Не забывай постфикс f в функциях

2022-06-18 12:57 UTC, Bonefest commented on project/engine/scene.cpp
> +        float cos_angle = 1.0f - 2.0f * solid_angle / glm::pi<float>();
Напиши как ты получил эту формулу? Мы и правда можем получить косинус, но не таким образом (посмотри внимательней на формулу телесного угла конуса)

2022-06-18 12:57 UTC, Bonefest commented on project/engine/scene.hpp
> +            return (glm::pi<float>() * radius * radius) / (L_length * L_length);
Это неправильная формула. Я предполагаю, что ты хотел использовать формулу A / d^2, где A - площадь "шапочки" конуса, но почему-то решил использовать pR^2. На самом деле, здесь идея в том, что у нас есть точка, на которую со всех сторон приходит свет. И есть источник света, который излучает свет и какая-то его часть приходит на эту точку. Так вот мы строим конус из этой точки (это будет вершина конуса) в направление источника света и считаем его телесный угол (Используя формулу телесного угла конуса). При этом у нас есть все необходимые знания (расстояние и радиус), чтобы посчитать угол конуса

По-хорошему, мы должны были бы посчитать PDF внутри этого конуса (который был бы равномерным), из него вывести CDF и запускать лучи из точки в направлении источника света используя этот CDF. Но мы, для простоты, запускаем всего один луч (центральный или к ближайшей точке, как захочется, все равно не полностью правильно)) ) и считаем, что это как бы свет приходящий со всего конуса.

2022-06-18 13:07 UTC, LeovanGit commented on project/engine/scene.cpp
> +        float cos_angle = 1.0f - 2.0f * solid_angle / glm::pi<float>();
sin(a) = R / L
cos(2a) = 1 - 2.0f * sin(a) * sina

2022-06-20 19:45 UTC, Bonefest commented on project/engine/scene.cpp
> +        float cos_angle = 1.0f - 2.0f * solid_angle / glm::pi<float>();
Понял, нам надо половина угла, т.е cosa

2022-06-27 03:46 UTC, mrindieperson requested changes

2022-06-27 03:46 UTC, mrindieperson commented on project/engine/scene.cpp
> +                type == IntersectedType::POINT_LIGHT)
Условие двойное

2022-06-27 03:46 UTC, mrindieperson commented on project/engine/scene.cpp
> +    // DIRECTIONAL LIGHTS
Вынеси эти циклы в разные функции Scene. computePointlights/Spotlights и т.д. Чтобы эту большую функцию разгрузить и можно было быстрее понять, о чём она и что где

2022-06-27 03:46 UTC, mrindieperson commented on project/engine/scene.cpp
> +        color += ambient * 2.0f * math::PI / float(SAMPLES_COUNT);
Для галочки проверь своё интегрирование так: вместо PBR() добавляй значение dot(N, sampleDir). То есть ты будешь интеграл косинуса по полусфере находить. В результате после деления на N и умножения на 2PI должно получиться просто PI (Поэтому в lambert диффуз там ещё делится на PI для нормализации энергии)

2022-06-27 03:46 UTC, mrindieperson commented on project/engine/scene.hpp
> +            float cosa = sqrtf(R_sqr) / L_length;
Поясни как нашёл эту формулу, выглядит некорректной. Напишу подсказку в чатике

2022-06-27 03:46 UTC, mrindieperson commented
- сделай сетку шариков горизонтальной
- добавь пару кубиков

2022-06-27 11:46 UTC, LeovanGit commented on project/engine/scene.cpp
> +        color += ambient * 2.0f * math::PI / float(SAMPLES_COUNT);
так и есть 👍

2022-06-27 12:46 UTC, mrindieperson commented on project/engine/scene.cpp
> +                ambient += PBR(nearest.normal,
Так, мы берём лучик света и хотим измерить, сколько света приходит с этого направления. И ты просто material_GI.albedo берёшь как энергию лучика? это не Global Illumination, у тебя все поверхности будто стали emissive. Ты должен посчитать энергию, сколько света приходит с направления луча. Либо там небо, либо там поверхность есть, для которой нужно расчитать, сколько от источников света отражается энергии в обратную сторону этого луча-семпла, это рекурсивный расчёт освещения

2022-07-01 18:26 UTC, mrindieperson approved these changes
Approved 👍

2022-07-04 06:02 UTC, Bonefest approved these changes

2022-07-04 12:47 UTC, merged