Homework 5
LeovanGit/render_internship pull request #5
Opened 2022-07-13 05:21 UTC by LeovanGit

2022-07-15 17:05 UTC, Bonefest requested changes

2022-07-15 17:05 UTC, Bonefest commented on project/engine/camera.cpp
> +         0,  0,  far / (far - near),           1.0f,
Попробуй всё-таки использовать reversed depth. Тебе по сути нужно будет очищать глубину не в 1, а в 0 и в depth stencil state использовать greater equal, ну и матрицы правильно использовать, как мы это раньше делали. Этот подход используется сейчас очень часто

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/texture_manager.cpp
> +    if (!instance) instance = new TextureManager();
Если init() вызывается второй раз, об этом нужно обязательно сообщить, это ведь ошибка. Посмотри, кстати, на spdlog - библиотека для логирования, она интегрируется за секунды и позволит тебе красиво выводить такого рода сообщения

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/window.cpp
> +    dss_desc.DepthFunc = D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS_EQUAL;
Вот это поменяй на greater equal после перехода на reversed z

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/shader.cpp
> +                                D3DCOMPILE_DEBUG | D3DCOMPILE_SKIP_OPTIMIZATION,
Предлагаю сделать дополнительный дефайн, например, SKIP_SHADERS_OPTIMIZATIONS и устанавливать ему эти флаги если мы в дебаге или зафорсили какой-то доп флаг (например объявили ещё FORCE_SKIP_SHADERS_OPTIMIZATIONS)

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/globals.hpp
> +    DxResPtr<ID3D11Buffer> vbo;
Это не часть globals, возможно, для этого задания это и подойдет, но вообще это project-specific вещи и им здесь не место

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/window.cpp
> +                                            tex_mgr->getTexture(1).sampler_state.get());
tex_mgr->getTexture(1) - такой код чреват разного рода ошибками. Это получается, что нам нужно как-то самим запоминать порядок инициализации и точно знать какой ид у какой текстуры. Тут вариантов несколько: либо при регистрации объекта возвращай его индекс, либо можешь сам этот ид задавать (например хранить данные в unordered_map и использовать string)

2022-07-15 17:05 UTC, Bonefest commented on project/engine/render/window.cpp
> +    shader_mgr->useShader(2);
С shader_mgr та же ситуация

2022-07-16 12:41 UTC, Bonefest approved these changes
Используй git submodule, т.к это, во-первых, не будет засорять дифф, во-вторых можно будет легче и быстрее обновить.

2022-07-18 16:22 UTC, mrindieperson requested changes

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    engine::TextureManager::init(); // TextureManager depends on Globals
Инкапсулируй инициализацию синглтонов в Engine::init(), потом пусть идёт Engine::deinit(), альтернативно можно сделать экземпляр класса Engine на стеке, который при выходе из main автоматом освободит всё, но должно гарантироваться, что всего один объект Engine может существовать за счёт статических полей типо Engine::s_inited

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    globals->initD3D();
Это внутри Globals должно быть

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    shader_mgr->registerShader("cube",
Убери это всё в initScene, зачем main загромождать

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    tex_mgr->registerTexture("cube", L"../textures/rubik_cube.dds");
Убери это всё в initScene, зачем main загромождать

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    camera.setPerspective(glm::radians(45.0f),
Убери это всё в initScene, зачем main загромождать

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/main.cpp
> +    globals->setConstBuffer(camera);
setConstBuffer в renderFrame можно убрать, но renderFrame долден быть методом Scene, а не окна, Window же класс общего пользования, зачем ей внутри рисовать какие-то кубики?

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/render/window.cpp
> +    globals->device_context4->Unmap(globals->const_buffer.ptr(), NULL);
Инкапсулируй в updatePerFrameBuffer

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/render/window.cpp
> +    globals->device_context4->ClearDepthStencilView(depth_stencil_view.ptr(),
Всё что относится к окну выше инкапсулируй в Window::clearFrame и и Window::bindRT

2022-07-18 16:22 UTC, mrindieperson commented on project/engine/render/window.cpp
> +    shader_mgr->useShader("skybox");
Всё что к небу - в Sky::render()

2022-07-18 16:24 UTC, mrindieperson commented on project/engine/shaders/cube.hlsl
> +SamplerState g_sampler;
Глобальный семплер в globals.hlsl

2022-07-18 16:25 UTC, mrindieperson commented on project/engine/render/window.cpp
> +                      tex_mgr->getTexture("cube").sampler_state.get());
Тебе не нужен отдельный семплер на каждую текстуру, объявляют несколько глобальных и используют их где надо

2022-07-20 15:41 UTC, mrindieperson commented on project/engine/source/controller.cpp
> +    tex_mgr->registerSampler("main", sampler_desc);
Это shared Sampler для разного использования, перенеси его в Globals и бинди в Globals::bind(), в TextureManager иметь мапу семплеров не имеет смысла, так как число семплеров ограниченно обычно итак и можно просто в Globals их всех хранить

Инициализация shared объектов в Globals::init должна быть

2022-07-20 15:42 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    tex_mgr->useSampler("main");
бинди в Globals::bind()

2022-07-20 15:43 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    globals->updatePerFrameBuffer();
Вызывай у инстанса просто bind функцию и там обновляй и бинди Per Frame Buffer

2022-07-20 15:45 UTC, mrindieperson commented on project/engine/source/render/sky.cpp
> +    m_texture->activate();
Имхо, activate не очень консистентное название. Globals::bind будет внутри вызывать bind, как ожидается. Globals::activate не понятно, что должно делать. А если Globals::bind внутри вызывает activate, это уже неконсистентность. Просто мелкое замечание про нейминги

2022-07-21 11:01 UTC, mrindieperson approved these changes
Approved :+1:

2022-07-21 11:30 UTC, merged