Homework 6
LeovanGit/render_internship pull request #6
Opened 2022-08-01 22:24 UTC by LeovanGit

2022-08-02 06:49 UTC, mrindieperson commented on project/engine/source/controller.cpp
> +    tex_mgr->registerTexture("fur", L"../engine/assets/Knight/dds/Fur_BaseColor.dds");
Убери registerTexture и используй просто getTexture, которая добавляет текстуру, если её ещё нет

2022-08-02 06:50 UTC, mrindieperson commented on project/engine/source/controller.cpp
> +    model_mgr->registerModel("knight", "../engine/assets/Knight/Knight.fbx");
registerModel аналогично

2022-08-02 06:55 UTC, mrindieperson commented on project/engine/source/controller.cpp
> +    scene->mesh_system.addModel(&model_mgr->getModel("knight"),
Просто vector\<Material\> perMesh передавай и один раз вызывай addInstance

2022-08-02 06:56 UTC, mrindieperson commented on project/engine/source/render/mesh_system.hpp
> +class MeshSystem
Пожалуй сделай MeshSystem синглтоном движка. Иначе если будет больше чем один инстанс MeshSystem, рендер будет не эффективным, а если система одна, она знаёт как эффективно рисовать всё, не нужна дополнительная группировка между системами

2022-08-02 07:04 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    // DRAW FLOOR
такие вот комментарии обычно кстати как раз и намекают, что это должно быть инкапсулировано в функцию drawFloor или вообще в класс Floor

2022-08-02 07:07 UTC, mrindieperson commented on project/engine/source/render/opaque_instances.cpp
> +    std::vector<Instance> instances;
Зачем дважды аллоцировать память сначала в векторе, потом в драйвере, если можно сразу Map вызвать у буффера и писать напрямую куда надо инстансы без лишнего копирования, как у меня в подсказке

2022-08-02 07:26 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    row_major float4x4 mesh_to_model;
g_

2022-08-02 20:11 UTC, Bonefest requested changes

2022-08-02 20:11 UTC, Bonefest commented on project/engine/source/render/opaque_instances.hpp
> +        Model * model;
Используй умные указатели

2022-08-02 20:11 UTC, Bonefest commented on project/engine/source/render/model.hpp
> +    std::vector<MeshRange> & get_meshes();
Называй своими именами, т.к ты пишешь здесь get_meshes, в другом месте пишешь коммент "add mesh ranges" и в итоге мне приходится смотреть что на самом деле здесь передаётся)

2022-08-02 20:11 UTC, Bonefest commented on project/engine/source/render/model.hpp
> +    std::vector<MeshRange> & get_meshes();
И старайся как-то в одном стиле именовать функции. Я лично пользуюсь чем-то похожим на google c++ style guide

2022-08-02 20:11 UTC, Bonefest commented on project/engine/source/controller.cpp
> +    scene->mesh_system.addModel(&model_mgr->getModel("knight"),
Согласен, мне, если честно, эти addModel вообще сначала показались нелогичными. Такой код трудно понять, т.к у тебя тут дополнительные знания про структуру этой модели

2022-08-03 13:13 UTC, mrindieperson commented
registerShader тоже поправь

2022-08-03 13:19 UTC, mrindieperson commented on project/engine/source/controller.cpp
> +    scene->mesh_system.addModel(&model_mgr->getModel("knight"),
Ну у нас просто нет здесь никаких файлов ассетов, которые внутри содержат, какая модель рисуется и с какими материалами на каждый меш, типо "red samurai" или "blue samurai", поэтому код инициализации вынужден задавать модель и per-mesh материалы, но этого достаточно

2022-08-03 16:01 UTC, mrindieperson commented
Ещё в addModel передавай последним параметром OpaqueInstances::Instance структуру, у которой внутри одна матрица

2022-08-03 16:05 UTC, mrindieperson commented
Вытащи depthstencil из Window, буфер глубины нужен рендеру, но не окну, у окна только цвет есть. А буфер глубины один может переиспользоваться для разных целей и не только глубину сцена хранить

2022-08-04 16:14 UTC, mrindieperson approved these changes

2022-08-04 18:59 UTC, Bonefest approved these changes

2022-08-04 20:03 UTC, merged