Homework 7
LeovanGit/render_internship pull request #7
Opened 2022-08-25 03:38 UTC by LeovanGit

2022-08-25 11:30 UTC, Bonefest requested changes
У тебя немного странно мышка работает: если задать направление, отпустить, затем опять задать направления - иногда бывает небольшой рывок.

2022-08-25 11:30 UTC, Bonefest commented on project/engine/shaders/opaque.hlsl
> +    output.TBN = TBN;
Лучше сделай немного иначе: а) Либо переводи в TBN пространство все вектора и точки б) Передавай T и B и затем рассчитывай TBN в пиксельном шейдере (UE так делает).

Это не должно сильно повлиять на перформанс, но для более тяжёлых мешей интерполирование аттрибутов может оказаться достаточно дорогим (или даже дороже самого пиксельного шейдера).

2022-08-25 11:30 UTC, Bonefest commented on project/engine/source/math/ray.cpp
> +    glm::vec3 normal = glm::normalize(glm::cross(V2 - V1, V3 - V1));
Посчитай v2 - v1 и v3 - v1 и переиспользуй потом

2022-08-25 11:30 UTC, Bonefest commented on project/engine/source/math/ray.cpp
> +    if (glm::dot(glm::cross(edge_1, edge_2), normal) <= 0) n = -normal;
Выглядит лишним. Мы ведь можем это гарантировать и так. Ещё советую посмотреть сюда http://www.r-5.org/files/books/computers/algo-list/realtime-3d/Christer_Ericson-Real-Time_Collision_Detection-EN.pdf - тут чуть быстрее реализация (стр. 190)

2022-08-25 11:30 UTC, Bonefest commented on project/engine/source/render/globals.cpp
>      if (per_mesh_buffer.valid()) return;
Попробуй инициализацию вынести отдельно от заполнения.

2022-08-25 11:30 UTC, Bonefest commented on project/engine/source/render/light_system.hpp
> +    glm::vec3 radianceFromIrradianceAtDistance(const glm::vec3 & irradiance,
Это чисто utility функция. Нам не нужен instance для неё. Сделай статической или вынеси.

2022-08-27 21:24 UTC, mrindieperson requested changes

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/source/render/emissive_instances.cpp
> +    glm::mat4 * dst = static_cast<glm::mat4 *>(mapped.pData);
А где radiance источника света?

Создай структуру GpuInstance в .hpp и добавь поля матрицы и float3 с паддингом radiance для emissive поверхности

В Opaque просто одна матрица

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/emissive.hlsl
> +    float3 g_radiance;
Почему emissive не может быть разной у разных сфер? Это per instance data

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/post_processing.hlsl
> +    float3 color = g_hdr_scene.Sample(g_sampler, input.uv);
Используй Load с целочисленными координатами

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/source/camera.hpp
>      float EV_100;
при чём тут EV100 в Camera, которая просто математический класс для работы с матрицами View/Proj?

Сделай Postprocess класс с методом resolve(sourceHDR, targetLDR), как объяснял

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/source/camera.hpp
>      float EV_100;
Postprocess передавай как 3-ий параметр в Scene::renderFrame, как и камеру, так как это дополнительная настройка отображения конкретной точки зрения

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/source/render/globals.cpp
> +            light_system->directional_lights[i].direction;
Зачем point_lights/directional_lights делать public? а .clear() можно сделать тут? сделай акссесор, который const& хоть возвращает

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +float calculateSolidAngle(float L_length,
Все общие функции расчёта освещения вынеси в lighting.hlsl, функцию calculatePointLights в том числе. Сделай просто вообще calculateLighting который уже calculatePointLights/calculateDirectionalLights вызывает

Material не надо переносить, он разный для разных шейдеров

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +        N = normalize(N * 2.0f - 1.0f); // [0; 1] -> [-1; 1]
не надо нормализовать, ниже же нормализуется

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    if (g_has_roughness_texture)
используй тернарник ?:

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    if (!g_is_directx_style_normal_map) bitangent *= -1.0f;
Зачем это в каждом пикселе делать, если можно в вершинном шейдере

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    material.fresnel = float3(g_F0_dielectric, g_F0_dielectric, g_F0_dielectric);
просто = g_F0_dielectric;
или уж float3(g_F0_dielectric);

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    float NL = clamp(dot(N, L), 0.0f, 1.0f);
clamp(x, 0, 1) это просто saturate(x), но это тут не нужно

Ты тут должен был max(x, 0.001) написать

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    float NV = clamp(dot(N, V), 0.0f, 1.0f);
max(x, 0.001)

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    float NH = clamp(dot(N, H), 0.0f, 1.0f);
max(x, 0.001)

2022-08-27 21:24 UTC, mrindieperson commented on project/engine/shaders/opaque.hlsl
> +    float cosa = sqrt(R_sqr) / L_length;
просто sqrt(1.0 - sina^2)

2022-08-31 09:38 UTC, mrindieperson commented on project/engine/source/render/post_process.cpp
> +    shader_mgr->bindShader("../engine/shaders/resolve.hlsl");
Зачем делать лишние операции поиска каждый раз, если можно в init один раз прикопать указатель на шейдер прямо в PostProcess?

2022-08-31 09:43 UTC, mrindieperson commented on project/engine/source/render/opaque_instances.cpp
>              Model::MeshRange & mesh_range = per_model.model->getMeshRange(i);
Тут выше аналогично не надо искать шейдер, прикопай указатель сразу в классе при инициализации.
shader_mgr->bindShader("../engine/shaders/opaque.hlsl");

2022-08-31 09:48 UTC, mrindieperson commented on project/engine/source/render/emissive_instances.hpp
> +        glm::vec3 radiance;
Паддинг добавь после radiance в 4 байт чтобы выравнивание до 16 байт было, в Input Layout будет float4 radiance, но .w не будет использована

2022-08-31 09:51 UTC, mrindieperson commented on project/engine/source/render/emissive_instances.hpp
> +        glm::vec3 radiance;
альтернативно можно вообще-то просто stride указать другой в InputLayout и оставить float3 в шейдере, padding будет в C++ только виден

2022-09-01 10:20 UTC, mrindieperson approved these changes
:+1:

2022-09-01 14:02 UTC, Bonefest approved these changes
Перепроверил, approved

2022-09-01 15:13 UTC, merged