Homework 8
LeovanGit/render_internship pull request #8
Opened 2022-09-14 07:24 UTC by LeovanGit

2022-09-18 21:40 UTC, mrindieperson commented
Мип уровень для отражений IBL выбирается неправильно, всегда 0. Это видно на "зеркалах". Там есть зеркала с разной формой спекулярных бликов от источников, но отражения везде как на идеальном зеркале, хотя там где размытй спекуляр должно быть и размытое отражения окружения

2022-09-18 21:42 UTC, mrindieperson commented
Слишком яркое окружение, вклад источников света не видно. Либо выбери потемнее кубмапу неба, либо сделай мощнее источники света, чтобы можно было через EV100 хоть искуственно сделать картинку будто вечерняя

2022-09-18 21:43 UTC, mrindieperson commented
Исправь `D3D11 WARNING: ID3D11DeviceContext::OMSetRenderTargets: Resource being set to OM DepthStencil is still bound on input!`

2022-09-18 21:55 UTC, mrindieperson commented on project/engine/shaders/lighting.hlsl
> +    pos_WS += N * normal_offset;
Пусть N не влияет на depth, меняй только .xy компоненты

2022-09-18 22:39 UTC, mrindieperson requested changes

2022-09-18 22:39 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    bindSquareViewport();
Инкапсулируй от bindSquareViewport до clearShadowMap в функцию renderShadows

2022-09-18 22:39 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    globals->device_context4->RSSetViewports(1, &shadow_map_viewport);
shadow_map_viewport делай полем LightSystem или ShadowSystem, как и DSV теней

2022-09-18 22:39 UTC, mrindieperson commented on project/engine/source/render/mesh_system.cpp
> +    for (uint32_t i = 0; i != shadow_cubemaps_count; ++i)
Делай это внутренним самым циклом, а не внешним

2022-09-19 09:06 UTC, Bonefest requested changes
Само приложение работает, вроде, даже как нужно)
Одно замечание: ворнингов от directx не должно быть.

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/controller.cpp
> +              std::vector<oi::Material>{oi::Material(
Чтобы не писать сотню опциональных параметров, ты можешь создать дополнительный конструктор или фабричную функцию. Например, material::createWithoutTextures(...) (над названием лучше подумать). Мне кажется, это называется фасад. В любом случае, это упростит код + сделает его более содержательным.

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/render/globals.cpp
>      per_frame_buffer_data.g_frustum_corners[1] = glm::vec4(top_left_WS, 1.0f);
На самом деле, всё, что относится конкретно к камере (позиции фрустума, различные матрицы, позиция, EV и т.д) должны выноситься в per-view буфер. Мне кажется, Эмиль когда-то это упоминал на лекции. Но т.к он явно этого не просил, оставь так (но лучше вынеси в отдельный, вспомогательный метод).

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/render/globals.cpp
>      per_frame_buffer_data.g_frustum_corners[1] = glm::vec4(top_left_WS, 1.0f);
Ещё, старайся делать методы достаточно небольшими. Если видишь, что метод логически состоит из набора разделов (заполнение общих данных, заполнение данных камеры, заполнение данных про тени) - разбивай на отдельные методы и вызывай их из общего. Таким образом ты как бы оставляешь комментарии, но при этом сами комментарии не пишешь. С моей стороны я буду читать код и сразу понимать, что здесь ты сделал А, здесь Б. Если меня интересует как работает Б - я открою соответствующий метод.

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/render/opaque_instances.cpp
> +    tex_mgr->getTexture("../engine/assets/environment/reflectance.dds")->bind(4);
Не очень нравится такой подход. Попробуй немного расширить функционал так, чтобы OpaqueInstances не знал какие текстуры конкретно использовать (как бы внедряй зависимость). Можешь, например, добавить ещё пару полей.

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/render/shader.cpp
> +    ID3D10Blob * geom_shader_buffer(0);
Старайся использовать version-agnostic типы. В данном случае ID3DBlob должен сработать.

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/scene.cpp
> +constexpr int SHADOW_MAP_SIZE = 1024;
Пиши в одном стиле, не нужно писать одно в капсе, второе без. Советую выбрать какой-то стиль и писать всё в нем (глянь на google style либо UE4 style или придумай свой)) )

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/scene.cpp
> +    dsb_desc.SampleDesc.Count = 4;
В идеале, это должно являться частью какой-нибудь структуры, которая хранит настройки движка. В твоём случае, достаточно для начала вынести это в отдельную переменную (правда остаётся проблема, например, с тем, как это передать в шейдера и что если кол-во сэмплов == 1).

2022-09-19 09:06 UTC, Bonefest commented on project/engine/source/scene.cpp
> +void Scene::initShadowMap(int size)
Очень большой вопрос должна ли заниматься сцена такими вещами. Тут лучше было бы выделить тени отдельно, т.к потенциально это будет сложно расширять (на разные типы теней). Представь себя через год, ты смотришь на коммит, в котором поменялась сцена, а ты хочешь найти изменения по теням. Даже подсознательно ты можешь откинуть этот файл и искать не там где надо.

2022-09-19 10:33 UTC, e-kabirov commented on project/engine/shaders/lighting.hlsl
> +    pos_WS.xy += N.xy * normal_offset;
Ой, это же World Space, не View Space, я тут неправильно сказал. Я подумаю  ещё сам, как это совместить лучше

2022-09-19 20:44 UTC, mrindieperson commented on project/engine/shaders/lighting.hlsl
> +    pos_WS.xy += N.xy * normal_offset;
в чатике я написал код как лучше

2022-09-19 20:52 UTC, mrindieperson commented on project/engine/source/scene.cpp
> +    mesh_system->renderShadowCubeMaps();
Зачем тут в двух разных строках это, если 2 в 1 можно засунуть

2022-09-19 21:43 UTC, mrindieperson commented on project/engine/shaders/lighting.hlsl
> +    float2 reflectanceLUT = g_reflectance.Sample(g_sampler, float2(NV, roughness));
roughness и NV перепутаны, Y нужно инвертировать, SampleLevel для 0 мипа используй, чекни, что семплер Clamp, а не Wrap, и вообще clamp/wrap семплеры явно добавь в globals, а не g_sampler общий используй

2022-09-20 13:42 UTC, LeovanGit commented on project/engine/source/scene.cpp
> +constexpr int SHADOW_MAP_SIZE = 1024;
Стараюсь писать, но иногда меня переклинивает 😀

2022-09-21 14:08 UTC, e-kabirov approved these changes
Approved :+1:

2022-09-22 18:58 UTC, Bonefest approved these changes
Approved

2022-09-22 19:49 UTC, merged